name: grownet
channels:
  - nvidia
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # 自动装好CUDA支持
  - pyg  # PyTorch Geometric（图神经核心库）
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - networkx
  - spacy
  - nltk
  - jupyterlab
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
      - transformers==4.36.2
      - sentence-transformers
      - faiss-cpu
      - wandb
      - gradio
      - openai
      - python-dotenv
      - pyvis==0.3.1
      - jinja2
      - langdetect
      - spacy
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
        - https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.7.1/zh_core_web_sm-3.7.1-py3-none-any.whl
