name: grownet
channels:
  - nvidia
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyg
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - networkx
  - spacy
  - nltk
  - jupyterlab
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
      - torch-geometric
      - transformers==4.36.2
      - sentence-transformers
      - faiss-cpu
      - wandb
      - gradio
      - openai
      - python-dotenv
      - pyvis==0.3.1
      - jinja2
      - langdetect
